permalink:    pretty
analytics_id: UA-19957147-1
title:        Dave Lim
description:  Personal website of Dave Lim
url:          http://dlimiter.net
author:       Dave Lim
email:        dave@dlimiter.net